### ISSUE TITLE
Install Warpspeed in profile.d

### ISSUE THREAD

**Issue by bbatsche** [warpspeed/warpspeed#1]
Rather than overwriting the user's `.bashrc` and `.bash_profile` why not put Warpspeed's hooks and settings in a file under `/etc/profile.d`? That way, shortcuts and features from Ubuntu are maintained, users can modify their shell without worrying about deleting any core features, and Warpspeed's configurations will be loaded automatically and without conflict.

**Comment by srhyne** [comment]
@bbatsche I'm doing my best to help answer this question so forgive me in advance if I'm missing something. 

I think @cturner80 set it up this way for the following reasons.. 

`/etc/profile.d/*.sh` files are system wide.....

If you look at the installed ~/.bashrc file (install all the things to see a great example) you'll see that all of the paths for NPM, Rbenv, Composer, etc are set to to the user's $HOME path. This method is probably less error prone when taking into account non-warpspeed user logins. It also allows for easier tweaking for jailed SSH users. 

Also, one thing I can't confirm is that profile.d/\* files are executed only in interactive shells and not in non-interactive shells. Is that right? But I guess it's a moot point because /etc/bash.bashrc sources them anyways. 

What are your thoughts @cturner80?

**Comment by christurnertv** [comment]
Hey guys, sorry for not responding to this when it was posted.

@srhyne You are correct that I was trying to maintain all configuration for the warpspeed user in isolation.

@bbatsche I was going for clarity of configuration over preservation of the default ubuntu profiles. I think a lot of folks do their own customization anyway, so they can just add it right in after the warpspeed stuff.

I just updated everything for Ubuntu 16.04. I'm going to leave this as-is for now unless it becomes a problem for other folks.
